name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying to gh-pages
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Clean install dependencies
        run: 
          npm cache clean --force
          rm -rf node_modules package-lock.json
          npm install
          npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to GitHub Pages
        run: |
          git config user.name "td-perso"
          git config user.email "thibaut.duby@outlook.fr"
          npm run gh-pages-deploy